repos:

  - repo: local
    hooks:
    - id: linter
      name: linter
      entry: bash -c 'cd backend && poetry run pylint ./cookingplanner/'
      language: system
      types: [python]

  - repo: local
    hooks:
    - id: tests
      name: tests
      entry: bash -c 'poetry run pytest'
      language: system
      types: [python]
      pass_filenames: false